trigger:
- develop

variables:
  dockerRegistryServiceConnection: 'a3d4b33a-62ef-4d37-b27a-1ab1849fb7dd'
  imageRepository: 'apicashflow'
  containerRegistry: 'apicashflowprod.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

pool:
  vmImage: $(vmImageName)

steps:
- task: DownloadSecureFile@1
  name: appsettings
  displayName: Download AppSettings.json
  inputs:
    secureFile: appsettings.Production.json
- script: |
    cp $(appsettings.secureFilePath) src/CashFlow.Api/appsettings.Production.json     
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      latest
      $(tag)